### ISSUE TITLE
Link from the magic button pointing to latest release leads to 'not found'

### ISSUE THREAD

**Issue by manuelbcd** [oracle-quickstart/oke-base#10]
README.md magic button

`[magic_oke_stack]: https://cloud.oracle.com/resourcemanager/stacks/create?zipUrl=https://github.com/oracle-quickstart/oke-base/releases/latest/download/oke-base-stack-latest.zip`

The url pointing to the latest package asset is not working anymore.

Greetings

**Comment by junior** [comment]
Thanks. Issue fixed with #11

**Comment by junior** [comment]
Actually fixed with #12
